In [9]:
import pandas as pd
import numpy as np

In [13]:
customer_orders = pd.read_csv(
    "../data/processed/customer_orders.csv"
)

customer_orders.shape

(99441, 16)

In [14]:
customer_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay,total_price,total_freight,payment_value,installments,review_score,customer_unique_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,-8.0,29.99,8.72,38.71,1.0,4.0,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,-6.0,118.70,22.76,141.46,1.0,4.0,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,-18.0,159.90,19.22,179.12,3.0,5.0,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.0,-13.0,45.00,27.20,72.20,1.0,5.0,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.0,-10.0,19.90,8.72,28.62,1.0,5.0,72632f0f9dd73dfee390c9b22eb56dd6

In [15]:
customer_orders.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'delivery_days',
 'delivery_delay',
 'total_price',
 'total_freight',
 'payment_value',
 'installments',
 'review_score',
 'customer_unique_id']

In [16]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/customer_orders.csv"
)

df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay,total_price,total_freight,payment_value,installments,review_score,customer_unique_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,-8.0,29.99,8.72,38.71,1.0,4.0,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,-6.0,118.70,22.76,141.46,1.0,4.0,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,-18.0,159.90,19.22,179.12,3.0,5.0,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.0,-13.0,45.00,27.20,72.20,1.0,5.0,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.0,-10.0,19.90,8.72,28.62,1.0,5.0,72632f0f9dd73dfee390c9b22eb56dd6

In [18]:
df["order_purchase_timestamp"] = pd.to_datetime(
    df["order_purchase_timestamp"]
)

In [19]:
snapshot_date = (
    df["order_purchase_timestamp"].max()
    + pd.Timedelta(days=1)
)

snapshot_date

Timestamp('2018-10-18 17:30:18')

In [20]:
rfm = df.groupby("customer_unique_id").agg({
    "order_purchase_timestamp": lambda x:
        (snapshot_date - x.max()).days,
    "order_id": "count",
    "payment_value": "sum"
})

In [21]:
rfm.columns = [
    "Recency",
    "Frequency",
    "Monetary"
]

rfm.head()

                                  Recency  Frequency  Monetary
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2      161          1    141.90
0000b849f77a49e4a4ce2b2a4ca5be3f      164          1     27.19
0000f46a3911fa3c0805444483337064      586          1     86.22
0000f6ccb0745a6a4b88665a16c9f078      370          1     43.62
0004aac84e0df4da2b147fca70cf8255      337          1    196.89

In [22]:
journey_features = df.groupby(
    "customer_unique_id"
).agg({
    "delivery_days":"mean",
    "delivery_delay":"mean",
    "review_score":"mean",
    "installments":"mean",
    "total_freight":"mean",
    "payment_value":"mean"
})

In [23]:
journey_features.columns = [
    "avg_delivery_days",
    "avg_delivery_delay",
    "avg_review_score",
    "avg_installments",
    "avg_freight",
    "avg_order_value"
]

In [24]:
purchase_count = (
    df.groupby("customer_unique_id")
      .size()
)

In [25]:
repeat_purchase = (
    purchase_count > 1
).astype(int)

In [26]:
repeat_purchase.value_counts()

0    93099
1     2997
Name: count, dtype: int64

In [27]:
customer_df = rfm.join(
    journey_features
)

customer_df["repeat_purchase"] = repeat_purchase

In [28]:
customer_df.head()

,Recency,Frequency,Monetary,avg_delivery_days,avg_delivery_delay,avg_review_score,avg_installments,avg_freight,avg_order_value,repeat_purchase
customer_unique_id,,,,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,161,1,141.90,6.0,-5.0,5.0,8.0,12.00,141.90,0
0000b849f77a49e4a4ce2b2a4ca5be3f,164,1,27.19,3.0,-5.0,4.0,1.0,8.29,27.19,0
0000f46a3911fa3c0805444483337064,586,1,86.22,25.0,-2.0,3.0,8.0,17.22,86.22,0
0000f6ccb0745a6a4b88665a16c9f078,370,1,43.62,20.0,-12.0,4.0,4.0,17.63,43.62,0
0004aac84e0df4da2b147fca70cf8255,337,1,196.89,13.0,-8.0,5.0,6.0,16.89,196.89,0

In [29]:
customer_df["repeat_purchase"].value_counts()

repeat_purchase
0    93099
1     2997
Name: count, dtype: int64

In [30]:
customer_df["repeat_purchase"].value_counts(normalize=True) * 100

repeat_purchase
0    96.881244
1     3.118756
Name: proportion, dtype: float64

In [31]:
customer_df.to_csv(
    "../data/processed/customer_features.csv"
)

In [32]:
customer_df.shape
customer_df.head()
customer_df["repeat_purchase"].value_counts()

repeat_purchase
0    93099
1     2997
Name: count, dtype: int64

In [33]:
customer_df.shape

(96096, 10)

In [34]:
customer_df.head()

,Recency,Frequency,Monetary,avg_delivery_days,avg_delivery_delay,avg_review_score,avg_installments,avg_freight,avg_order_value,repeat_purchase
customer_unique_id,,,,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,161,1,141.90,6.0,-5.0,5.0,8.0,12.00,141.90,0
0000b849f77a49e4a4ce2b2a4ca5be3f,164,1,27.19,3.0,-5.0,4.0,1.0,8.29,27.19,0
0000f46a3911fa3c0805444483337064,586,1,86.22,25.0,-2.0,3.0,8.0,17.22,86.22,0
0000f6ccb0745a6a4b88665a16c9f078,370,1,43.62,20.0,-12.0,4.0,4.0,17.63,43.62,0
0004aac84e0df4da2b147fca70cf8255,337,1,196.89,13.0,-8.0,5.0,6.0,16.89,196.89,0

In [35]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96096 entries, 0000366f3b9a7992bf8c76cfdf3221e2 to ffffd2657e2aad2907e67c3e9daecbeb
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Recency             96096 non-null  int64
 1   Frequency           96096 non-null  int64
 2   Monetary            96096 non-null  float64
 3   avg_delivery_days   93356 non-null  float64
 4   avg_delivery_delay  93356 non-null  float64
 5   avg_review_score    95380 non-null  float64
 6   avg_installments    96095 non-null  float64
 7   avg_freight         95420 non-null  float64
 8   avg_order_value     96095 non-null  float64
 9   repeat_purchase     96096 non-null  int64
dtypes: float64(7), int64(3)
memory usage: 8.1+ MB

In [36]:
customer_df.isnull().sum()

Recency                  0
Frequency                0
Monetary                 0
avg_delivery_days     2740
avg_delivery_delay    2740
avg_review_score       716
avg_installments         1
avg_freight            676
avg_order_value          1
repeat_purchase          0
dtype: int64

In [37]:
customer_df.shape
customer_df.info()
customer_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 96096 entries, 0000366f3b9a7992bf8c76cfdf3221e2 to ffffd2657e2aad2907e67c3e9daecbeb
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Recency             96096 non-null  int64
 1   Frequency           96096 non-null  int64
 2   Monetary            96096 non-null  float64
 3   avg_delivery_days   93356 non-null  float64
 4   avg_delivery_delay  93356 non-null  float64
 5   avg_review_score    95380 non-null  float64
 6   avg_installments    96095 non-null  float64
 7   avg_freight         95420 non-null  float64
 8   avg_order_value     96095 non-null  float64
 9   repeat_purchase     96096 non-null  int64
dtypes: float64(7), int64(3)
memory usage: 8.1+ MB

Recency                  0
Frequency                0
Monetary                 0
avg_delivery_days     2740
avg_delivery_delay    2740
avg_review_score       716
avg_installments         1
avg_freight            676
avg_order_value          1
repeat_purchase          0
dtype: int64

In [38]:
customer_df[
    customer_df["avg_delivery_days"].isna()
].head()

,Recency,Frequency,Monetary,avg_delivery_days,avg_delivery_delay,avg_review_score,avg_installments,avg_freight,avg_order_value,repeat_purchase
customer_unique_id,,,,,,,,,,
001ae44fa04911a9e9577356dce6c63c,345,1,116.23,NaN,NaN,NaN,1.0,16.33,116.23,0
0029bd580d3012618731f5abb174a07f,350,1,52.38,NaN,NaN,2.0,1.0,12.48,52.38,0
004ad212c650c96c8a48f30855a7bcb8,389,1,25.90,NaN,NaN,1.0,1.0,NaN,25.90,0
0071f46a072a9ae25bbe4438b15efe9c,624,1,174.54,NaN,NaN,3.0,4.0,NaN,174.54,0
009a0802534f904b40b9d512b49794e1,336,1,91.29,NaN,NaN,5.0,1.0,14.29,91.29,0

In [39]:
df["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [40]:
df_delivered = df[
    df["order_status"] == "delivered"
].copy()

In [41]:
df_delivered.shape

(96478, 16)

In [42]:
df_delivered["order_purchase_timestamp"] = pd.to_datetime(
    df_delivered["order_purchase_timestamp"]
)

In [43]:
snapshot_date = (
    df_delivered["order_purchase_timestamp"].max()
    + pd.Timedelta(days=1)
)

In [44]:
rfm = df_delivered.groupby("customer_unique_id").agg({
    "order_purchase_timestamp": lambda x:
        (snapshot_date - x.max()).days,
    "order_id": "count",
    "payment_value": "sum"
})

rfm.columns = [
    "Recency",
    "Frequency",
    "Monetary"
]

In [45]:
journey_features = df_delivered.groupby(
    "customer_unique_id"
).agg({
    "delivery_days":"mean",
    "delivery_delay":"mean",
    "review_score":"mean",
    "installments":"mean",
    "total_freight":"mean",
    "payment_value":"mean"
})

journey_features.columns = [
    "avg_delivery_days",
    "avg_delivery_delay",
    "avg_review_score",
    "avg_installments",
    "avg_freight",
    "avg_order_value"
]

In [46]:
purchase_count = (
    df_delivered.groupby("customer_unique_id")
    .size()
)

repeat_purchase = (
    purchase_count > 1
).astype(int)

In [47]:
customer_df = rfm.join(journey_features)

customer_df["repeat_purchase"] = repeat_purchase

In [48]:
customer_df.isnull().sum()

Recency                 0
Frequency               0
Monetary                0
avg_delivery_days       8
avg_delivery_delay      8
avg_review_score      603
avg_installments        1
avg_freight             0
avg_order_value         1
repeat_purchase         0
dtype: int64